### ISSUE TITLE
v1.1 Release Schedule - Details

### ISSUE THREAD

**Issue by superhawk610** [superhawk610/multicast#27]
This issue will serve as a hub for tracking/discussion relating to the 1.1 release milestone.

Due Date: **December 10, 2017**

The next minor release will clean up some iffy code and add in system-wide error handling for debugging through the GUI.

This should close the following issues:
- [x] `toString` error when assigning newly-created channels to a device (#26)
- [x] add error page when Chromecast fails to load hub app or loses connection (#19)
- [x] display error message when iframe cannot load due to `X-Frame-Options` header (#1)

**Comment by superhawk610** [comment]
Pushing this back a week due to personal time constraints.

**Comment by superhawk610** [comment]
Instead of writing increasingly obfuscated code, I believe it makes more sense to drop back and correct some core problems before they're allowed to get out of hand. Before progressing with this milestone, I am drawing out all functionality into modules under `app/lib`, and moving routing from `app/main.js` to `app/routes`.

You can follow along with my progress on the `wip` branch.

**Comment by superhawk610** [comment]
committed - #36
